# Task 4: Green deployment (outer) version 1.1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment-green
  labels:
    app: messaging-app
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
      color: green
  template:
    metadata:
      labels:
        app: messaging-app
        color: green
    spec:
      containers:
        - name: messaging-app
          image: your-dockerhub-username/messaging_app:1.1
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet: { path: /healthz/, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz/, port: 8000 }
            initialDelaySeconds: 30
            periodSeconds: 30
